"""remove unused column

Revision ID: 210b12fd65e1
Revises: 8de95a752a5e
Create Date: 2025-08-06 23:17:28.027442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '210b12fd65e1'
down_revision: Union[str, Sequence[str], None] = '8de95a752a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_form_detections_domain_name'), table_name='contact_form_detections')
    op.drop_table('contact_form_detections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_form_detections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('domain_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('website_antibot_detection', sa.BOOLEAN(), nullable=False),
    sa.Column('website_antibot_details', sa.TEXT(), nullable=True),
    sa.Column('form_url', sa.TEXT(), nullable=False),
    sa.Column('contact_form_present', sa.BOOLEAN(), nullable=False),
    sa.Column('form_antibot_detection', sa.BOOLEAN(), nullable=False),
    sa.Column('form_antibot_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('form_antibot_details', sa.TEXT(), nullable=True),
    sa.Column('form_fields', sqlite.JSON(), nullable=True),
    sa.Column('field_selectors', sqlite.JSON(), nullable=True),
    sa.Column('submit_button_selector', sa.VARCHAR(length=500), nullable=True),
    sa.Column('detection_date', sa.DATETIME(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.Column('form_method', sa.VARCHAR(length=10), nullable=True),
    sa.Column('form_action', sa.TEXT(), nullable=True),
    sa.Column('detection_confidence', sa.FLOAT(), nullable=True),
    sa.Column('detection_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_form_detections_domain_name'), 'contact_form_detections', ['domain_name'], unique=False)
    # ### end Alembic commands ###
