"""add_task_id_and_task_status_to_form_submission

Revision ID: 52de138d7ed5
Revises: b06b108b9a25
Create Date: 2025-08-07 10:58:23.557057

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "52de138d7ed5"
down_revision: str | Sequence[str] | None = "b06b108b9a25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_form_submissions_domain"), table_name="form_submissions")
    op.drop_index(op.f("ix_form_submissions_mission_id"), table_name="form_submissions")
    op.drop_table("form_submissions")
    op.drop_index(
        op.f("ix_contact_form_detections_domain_name"),
        table_name="contact_form_detections",
    )
    op.drop_table("contact_form_detections")
    op.drop_table("missions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "missions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("pre_defined_fields", sqlite.JSON(), nullable=False),
        sa.Column("created_date", sa.DATETIME(), nullable=False),
        sa.Column("submitted_date", sa.DATETIME(), nullable=True),
        sa.Column("last_updated", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contact_form_detections",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("domain_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("website_antibot_detection", sa.BOOLEAN(), nullable=False),
        sa.Column("form_url", sa.TEXT(), nullable=True),
        sa.Column("contact_form_present", sa.BOOLEAN(), nullable=False),
        sa.Column("form_antibot_detection", sa.BOOLEAN(), nullable=False),
        sa.Column("form_antibot_type", sa.VARCHAR(length=100), nullable=True),
        sa.Column("form_fields", sqlite.JSON(), nullable=True),
        sa.Column("field_selectors", sqlite.JSON(), nullable=True),
        sa.Column("submit_button_selector", sa.VARCHAR(length=500), nullable=True),
        sa.Column("detection_date", sa.DATETIME(), nullable=False),
        sa.Column("last_updated", sa.DATETIME(), nullable=False),
        sa.Column("form_action", sa.TEXT(), nullable=True),
        sa.Column("detection_status", sa.VARCHAR(length=50), nullable=False),
        sa.Column("task_id", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contact_form_detections_domain_name"),
        "contact_form_detections",
        ["domain_name"],
        unique=False,
    )
    op.create_table(
        "form_submissions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("mission_id", sa.INTEGER(), nullable=False),
        sa.Column("domain", sa.VARCHAR(length=255), nullable=False),
        sa.Column("submitted_fields", sqlite.JSON(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), nullable=False),
        sa.Column("submission_date", sa.DATETIME(), nullable=False),
        sa.Column("last_updated", sa.DATETIME(), nullable=False),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column("response_data", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_form_submissions_mission_id"),
        "form_submissions",
        ["mission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_form_submissions_domain"), "form_submissions", ["domain"], unique=False
    )
    # ### end Alembic commands ###
