"""Initial migration

Revision ID: 7a553902364a
Revises: 
Create Date: 2025-08-07 03:30:15.664257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a553902364a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_form_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('website_antibot_detection', sa.Boolean(), nullable=False),
    sa.Column('form_url', sa.Text(), nullable=True),
    sa.Column('contact_form_present', sa.Boolean(), nullable=False),
    sa.Column('form_antibot_detection', sa.Boolean(), nullable=False),
    sa.Column('form_antibot_type', sa.String(length=100), nullable=True),
    sa.Column('form_fields', sa.JSON(), nullable=True),
    sa.Column('field_selectors', sa.JSON(), nullable=True),
    sa.Column('submit_button_selector', sa.String(length=500), nullable=True),
    sa.Column('detection_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('form_action', sa.Text(), nullable=True),
    sa.Column('detection_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_form_detections_domain_name'), 'contact_form_detections', ['domain_name'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pre_defined_fields', sa.JSON(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('submitted_fields', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_domain'), 'form_submissions', ['domain'], unique=False)
    op.create_index(op.f('ix_form_submissions_mission_id'), 'form_submissions', ['mission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_submissions_mission_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_domain'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_contact_form_detections_domain_name'), table_name='contact_form_detections')
    op.drop_table('contact_form_detections')
    # ### end Alembic commands ###
