"""Initial migration: Create ContactFormDetection table

Revision ID: 8de95a752a5e
Revises: 
Create Date: 2025-07-31 22:27:18.334585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de95a752a5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_form_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('website_antibot_detection', sa.Boolean(), nullable=False),
    sa.Column('website_antibot_details', sa.Text(), nullable=True),
    sa.Column('form_url', sa.Text(), nullable=False),
    sa.Column('contact_form_present', sa.Boolean(), nullable=False),
    sa.Column('form_antibot_detection', sa.Boolean(), nullable=False),
    sa.Column('form_antibot_type', sa.String(length=100), nullable=True),
    sa.Column('form_antibot_details', sa.Text(), nullable=True),
    sa.Column('form_fields', sa.JSON(), nullable=True),
    sa.Column('field_selectors', sa.JSON(), nullable=True),
    sa.Column('submit_button_selector', sa.String(length=500), nullable=True),
    sa.Column('detection_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('form_method', sa.String(length=10), nullable=True),
    sa.Column('form_action', sa.Text(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('detection_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_form_detections_domain_name'), 'contact_form_detections', ['domain_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_form_detections_domain_name'), table_name='contact_form_detections')
    op.drop_table('contact_form_detections')
    # ### end Alembic commands ###
